server.port=8081

# Gemini Configuration
gemini.api.key=AIzaSyCaCuJxcrqxBDPdQNcegDs24i49PYAhi2U
gemini.api.model=gemini-2.5-flash

# CORS
app.cors.allowed-origins=http://localhost:4200

# Logging
logging.level.com.aitestgen=DEBUG
